### ISSUE TITLE
Not an issue, but why not use spread operator instead of apply?

### ISSUE THREAD

**Issue by skanne** [websemantics/hyperapp-lifecycle#1]
Hi, I was looking at your code and found that (after having embraced ES6 parlance completely) this line https://github.com/websemantics/hyperapp-lifecycle/blob/a1b511dbc2ff109fddf25496152b6a73434617b0/src/index.js#L26 looked weird to me. Why use `module.h.apply(null, arguments)` if in ES6 you can express it more elegantly with `module.h(...arguments)`?

See for instance here: https://derickbailey.com/2015/11/16/kill-apply-with-the-spread-operator/

**Comment by websemantics** [comment]
Hi @skanne, great question! 

Initially, I wrote this following the code style of most of the code I've seen written by [Hyperapp](https://github.com/jorgebucaran/hyperapp/blob/master/src/index.js) community and didn't want to go all esnext on my first extension. If that makes any sense :)

Or this,  `{l: (...args) => withChildLifeCycle(module.h(...args)}`

Eventually, I'll update the code as you make a good point,
